/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const VendorInquiry = IDL.Record({
  'contactPerson' : IDL.Text,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'monthlyVolume' : IDL.Nat,
  'materialType' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllVendorInquiries' : IDL.Func([], [IDL.Vec(VendorInquiry)], ['query']),
  'getVendorInquiriesByMaterialType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VendorInquiry)],
      ['query'],
    ),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'submitVendorInquiry' : IDL.Func([VendorInquiry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const VendorInquiry = IDL.Record({
    'contactPerson' : IDL.Text,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'monthlyVolume' : IDL.Nat,
    'materialType' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllVendorInquiries' : IDL.Func([], [IDL.Vec(VendorInquiry)], ['query']),
    'getVendorInquiriesByMaterialType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VendorInquiry)],
        ['query'],
      ),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'submitVendorInquiry' : IDL.Func([VendorInquiry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };