/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface VendorInquiry {
  'contactPerson' : string,
  'businessName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'monthlyVolume' : bigint,
  'materialType' : string,
}
export interface _SERVICE {
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllVendorInquiries' : ActorMethod<[], Array<VendorInquiry>>,
  'getVendorInquiriesByMaterialType' : ActorMethod<
    [string],
    Array<VendorInquiry>
  >,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'submitVendorInquiry' : ActorMethod<[VendorInquiry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];